import { StyleSheet } from 'react-native'
import { colors } from '../../theme/colors'

export const styles = StyleSheet.create({
  content: {
    paddingBottom: 26,
  },
  eyebrow: {
    color: '#ffd6bf',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  title: {
    color: '#f8fbff',
    fontSize: 30,
    fontWeight: '800',
    marginTop: 8,
    lineHeight: 34,
  },
  subtitle: {
    color: '#d4e3f9',
    marginTop: 8,
    lineHeight: 20,
    fontSize: 14,
  },
  sessionRow: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#355a80',
    borderRadius: 12,
    backgroundColor: '#14314d',
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sessionText: {
    color: '#c7dcf8',
    fontSize: 12,
    flex: 1,
  },
  sessionButton: {
    borderWidth: 1,
    borderColor: '#4c7299',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#102b44',
  },
  sessionButtonText: {
    color: '#f5f9ff',
    fontWeight: '700',
    fontSize: 12,
  },
  roleRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  roleButton: {
    borderWidth: 1,
    borderColor: '#365a80',
    borderRadius: 999,
    backgroundColor: '#14304b',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  roleButtonActive: {
    borderColor: '#ffc6aa',
    backgroundColor: '#ffe4d4',
  },
  roleButtonText: {
    color: '#c7dcf8',
    fontWeight: '700',
    fontSize: 13,
  },
  roleButtonTextActive: {
    color: '#8c3c1d',
  },
  tabsWrap: {
    marginTop: 14,
  },
  tabsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 8,
  },
  tabButton: {
    borderWidth: 1,
    borderColor: '#365a80',
    borderRadius: 999,
    backgroundColor: '#183653',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  tabButtonActive: {
    borderColor: '#99c1ff',
    backgroundColor: '#24507a',
  },
  tabButtonText: {
    color: '#bfd7f9',
    fontSize: 13,
    fontWeight: '700',
  },
  tabButtonTextActive: {
    color: '#ffffff',
  },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 16,
    marginTop: 16,
  },
  cardTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 24,
  },
  cardSubtitle: {
    color: colors.muted,
    marginTop: 6,
    lineHeight: 19,
    fontSize: 13,
  },
  ucRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 12,
  },
  ucPill: {
    borderWidth: 1,
    borderColor: '#bed6f9',
    backgroundColor: '#eaf2ff',
    color: '#2d5a95',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    overflow: 'hidden',
    fontSize: 11,
    fontWeight: '700',
  },
  sectionLabel: {
    color: colors.muted,
    marginTop: 14,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontWeight: '700',
    fontSize: 11,
  },
  rowBetween: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#e4ecfb',
    borderRadius: 12,
    padding: 10,
    backgroundColor: '#f9fcff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  rowTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  rowMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  amount: {
    color: colors.text,
    fontWeight: '800',
    fontSize: 14,
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '700',
    overflow: 'hidden',
  },
  statusSuccess: {
    backgroundColor: '#eaf9f3',
    color: colors.success,
  },
  statusWarning: {
    backgroundColor: '#fff5da',
    color: '#9f6d00',
  },
  statusInfo: {
    backgroundColor: '#e8f1ff',
    color: '#225ea6',
  },
  statusDanger: {
    backgroundColor: '#ffe9e5',
    color: colors.danger,
  },
  miniGrid: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 8,
  },
  miniCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#dbe8fa',
    borderRadius: 12,
    backgroundColor: '#f7fbff',
    padding: 10,
  },
  miniLabel: {
    color: colors.muted,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  miniValue: {
    color: colors.text,
    marginTop: 6,
    fontWeight: '800',
    fontSize: 16,
  },
  mapMock: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#ccdffd',
    backgroundColor: '#dfeeff',
    padding: 14,
    minHeight: 150,
    justifyContent: 'space-between',
  },
  mapRoad: {
    height: 3,
    borderRadius: 999,
    backgroundColor: '#72a7f0',
    marginVertical: 6,
  },
  mapPinRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  mapPin: {
    color: '#1f4f8f',
    fontWeight: '700',
    fontSize: 12,
  },
  timeline: {
    marginTop: 10,
    gap: 10,
  },
  timelineItem: {
    borderLeftWidth: 3,
    borderLeftColor: '#d2e4ff',
    paddingLeft: 10,
  },
  timelineTitle: {
    color: colors.text,
    fontWeight: '700',
    fontSize: 13,
  },
  timelineMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
})
