import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f2f4f7' },
  screen: { flex: 1, backgroundColor: '#f2f4f7' },
  homeHeader: {
    backgroundColor: '#2f6fe9',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 16,
    shadowColor: '#1d4ed8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  homeHeaderTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  brand: { color: '#ffffff', fontSize: 26, fontWeight: '800', letterSpacing: -0.5 },
  subtitle: { color: '#dbe7ff', fontSize: 13, marginTop: 1 },
  profileButton: {
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileIcon: { color: '#ffffff', fontSize: 17 },
  searchField: {
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.28)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchIcon: { color: '#bfd1ff', fontSize: 14 },
  searchText: { color: '#dbe7ff', fontSize: 14, fontWeight: '500' },
  searchInput: {
    flex: 1,
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
    padding: 0,
  },
  filterRow: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  filterInput: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.28)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: '#ffffff',
    fontSize: 13,
  },
  filterApply: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  filterApplyText: {
    color: '#1d4ed8',
    fontWeight: '800',
    fontSize: 12,
  },
  filterReset: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.45)',
  },
  filterResetText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 12,
  },
  offlineBanner: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#facc15',
    backgroundColor: '#fef9c3',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  offlineBannerText: {
    color: '#854d0e',
    fontSize: 13,
    fontWeight: '700',
  },
  notificationBanner: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  notificationBannerTitle: {
    color: '#1d4ed8',
    fontSize: 13,
    fontWeight: '800',
  },
  notificationBannerText: {
    color: '#1e40af',
    fontSize: 12,
    marginTop: 2,
  },
  pushChip: {
    marginTop: 8,
    color: 'rgba(255, 255, 255, 0.78)',
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
  },
  headerActionsRow: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'stretch',
  },
  activeOrderBtn: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    paddingVertical: 11,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  activeOrderBtnText: {
    color: '#1d4ed8',
    fontWeight: '800',
    fontSize: 13,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusDotLive: {
    backgroundColor: '#16a34a',
  },
  statusDotConnecting: {
    backgroundColor: '#f59e0b',
  },
  statusDotOffline: {
    backgroundColor: '#94a3b8',
  },
  scrollContent: { paddingHorizontal: 14, paddingTop: 18, paddingBottom: 24 },
  sectionTitle: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  mutedText: { color: '#64748b', fontSize: 14, marginBottom: 8 },
  restaurantCard: {
    borderWidth: 1,
    borderColor: '#e6e9ef',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    marginBottom: 10,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  restaurantStripe: {
    height: 3,
    backgroundColor: '#ff6900',
  },
  restaurantBody: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  restaurantIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#fff3e6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  restaurantIcon: { fontSize: 22 },
  restaurantInfo: {
    flex: 1,
    minWidth: 0,
  },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  restaurantName: { color: '#0f172a', fontSize: 15, fontWeight: '700' },
  ratingPill: {
    borderRadius: 999,
    backgroundColor: '#d9fbe4',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  ratingText: { color: '#14803c', fontSize: 12, fontWeight: '700' },
  cuisine: { color: '#64748b', fontSize: 12, marginTop: 2 },
  menuHeader: {
    backgroundColor: '#2f6fe9',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 14,
    shadowColor: '#1d4ed8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  backButton: {
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 6,
    marginLeft: -6,
  },
  backArrow: { color: '#ffffff', fontSize: 22, fontWeight: '700' },
  menuHeaderTitle: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '800',
    marginTop: 2,
    letterSpacing: -0.4,
  },
  categoryStrip: {
    maxHeight: 52,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e6e9ef',
  },
  categoryStripContent: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 6,
  },
  categoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: '#f1f5f9',
    marginRight: 6,
  },
  categoryChipActive: {
    backgroundColor: '#2f6fe9',
  },
  categoryChipText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
  },
  categoryChipTextActive: {
    color: '#ffffff',
  },
  menuCard: {
    borderWidth: 1,
    borderColor: '#e6e9ef',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  menuThumb: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#fff3e6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  menuThumbEmoji: { fontSize: 22 },
  menuInfo: { flex: 1, minWidth: 0 },
  menuName: { color: '#0f172a', fontSize: 15, fontWeight: '700' },
  menuDescription: { color: '#64748b', fontSize: 12, marginTop: 2 },
  menuPrice: { color: '#ff5f00', fontSize: 14, fontWeight: '800', marginTop: 4 },
  menuRate: { color: '#16a34a', fontSize: 11, marginTop: 2, fontWeight: '600' },
  addButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#2f6fe9',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  addButtonText: { color: '#ffffff', fontSize: 20, lineHeight: 22, fontWeight: '700' },
  withCartBar: { paddingBottom: 96 },
  cartBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 12,
    borderRadius: 12,
    backgroundColor: '#2f6fe9',
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#1d4ed8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 5,
  },
  cartBarText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  cartScroll: { flexGrow: 1 },
  cartCard: {
    borderWidth: 1,
    borderColor: '#e6e9ef',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  cartInfo: { flex: 1, minWidth: 0 },
  cartPrice: { color: '#64748b', fontSize: 13, marginTop: 2 },
  qtyControl: {
    marginTop: 10,
    alignSelf: 'flex-start',
    height: 32,
    borderRadius: 999,
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  qtyButton: {
    width: 26,
    height: 26,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyText: { color: '#1d4ed8', fontSize: 16, lineHeight: 18, fontWeight: '700' },
  qtyValue: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '700',
    minWidth: 20,
    textAlign: 'center',
  },
  removeButton: {
    paddingHorizontal: 6,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  removeText: { color: '#ef4444', fontSize: 22, lineHeight: 22 },
  checkoutBar: {
    borderTopWidth: 1,
    borderTopColor: '#e6e9ef',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 6,
  },
  summaryLine: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  summaryLabel: { color: '#64748b', fontSize: 13 },
  summaryValue: { color: '#0f172a', fontSize: 13, fontWeight: '600' },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    borderTopWidth: 1,
    borderTopColor: '#e6e9ef',
    paddingTop: 10,
    marginTop: 6,
  },
  totalLabel: { color: '#0f172a', fontSize: 17, fontWeight: '800' },
  totalValue: { color: '#0f172a', fontSize: 20, fontWeight: '800', letterSpacing: -0.4 },
  orderButton: {
    marginTop: 14,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#2f6fe9',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1d4ed8',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 3,
  },
  orderButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '800', letterSpacing: 0.3 },
  trackHeader: {
    backgroundColor: '#2f6fe9',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 14,
    shadowColor: '#1d4ed8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 4,
  },
  trackTitle: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '800',
    marginTop: 2,
    letterSpacing: -0.4,
  },
  trackSub: { color: '#dbe7ff', fontSize: 13, marginTop: 2 },
  trackCard: {
    borderWidth: 1,
    borderColor: '#e6e9ef',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    padding: 14,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  trackSummaryTitle: { color: '#0f172a', fontSize: 16, fontWeight: '800' },
  trackSummarySub: { color: '#64748b', fontSize: 13, marginTop: 4 },
  trackDetailsCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e6e9ef',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    padding: 14,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  successBanner: {
    borderRadius: 12,
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 10,
    alignItems: 'center',
  },
  paymentSuccessBanner: {
    marginBottom: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  paymentSuccessTitle: {
    color: '#15803d',
    fontSize: 14,
    fontWeight: '800',
  },
  paymentSuccessText: {
    color: '#166534',
    fontSize: 12.5,
    marginTop: 3,
  },
  successBannerText: { color: '#15803d', fontSize: 13, fontWeight: '700' },
  successText: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 14,
    backgroundColor: '#ecfdf5',
    borderColor: '#16a34a',
    borderWidth: 1,
    borderRadius: 10,
    color: '#166534',
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontWeight: '700',
  },
  errorText: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 14,
    backgroundColor: '#fef2f2',
    borderColor: '#dc2626',
    borderWidth: 1,
    borderRadius: 10,
    color: '#991b1b',
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bellButton: {
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellIcon: { color: '#ffffff', fontSize: 17 },
  bellBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    paddingHorizontal: 4,
    backgroundColor: '#dc2626',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  inboxBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    justifyContent: 'flex-end',
  },
  inboxCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 18,
    maxHeight: '90%',
  },
  inboxHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  inboxTitle: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: '900',
  },
  inboxSubtitle: {
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
  },
  inboxClose: {
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inboxCloseText: {
    color: '#475569',
    fontSize: 22,
    lineHeight: 22,
  },
  inboxActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
    marginBottom: 8,
  },
  inboxFilter: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
  },
  inboxFilterActive: {
    backgroundColor: '#3479ed',
    borderColor: '#3479ed',
  },
  inboxFilterText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
  },
  inboxFilterTextActive: {
    color: '#ffffff',
  },
  inboxList: {
    marginTop: 4,
    maxHeight: 480,
  },
  inboxListContent: {
    paddingBottom: 12,
  },
  inboxEmpty: {
    color: '#64748b',
    fontSize: 13,
    paddingVertical: 12,
  },
  inboxItem: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  inboxItemRead: {
    backgroundColor: '#ffffff',
    borderColor: '#e2e8f0',
  },
  inboxItemUnread: {
    backgroundColor: '#eff6ff',
    borderColor: '#bfdbfe',
  },
  inboxItemTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  inboxItemTitle: {
    flex: 1,
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '800',
  },
  inboxItemBadge: {
    fontSize: 10,
    fontWeight: '800',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    overflow: 'hidden',
  },
  inboxItemBadgeUnread: {
    backgroundColor: '#1d4ed8',
    color: '#ffffff',
  },
  inboxItemBadgeRead: {
    backgroundColor: '#e2e8f0',
    color: '#475569',
  },
  inboxItemMessage: {
    marginTop: 4,
    color: '#475569',
    fontSize: 13,
  },
  inboxItemFooter: {
    marginTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inboxItemTimestamp: {
    color: '#64748b',
    fontSize: 11,
  },
  inboxItemAction: {
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '800',
  },
  inboxItemReadLabel: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '700',
  },
  ordersLink: {
    flex: 1,
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.32)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ordersLinkText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  orderCard: {
    borderWidth: 1,
    borderColor: '#e6e9ef',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    padding: 14,
    marginBottom: 10,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  orderCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  orderCardHeading: {
    flex: 1,
    minWidth: 0,
  },
  orderCardRestaurant: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '700',
  },
  orderCardDate: {
    color: '#94a3b8',
    fontSize: 11.5,
    marginTop: 2,
  },
  orderStatusChip: {
    fontSize: 10,
    fontWeight: '800',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  orderStatusOk: {
    backgroundColor: '#dcfce7',
    color: '#166534',
  },
  orderStatusOff: {
    backgroundColor: '#fee2e2',
    color: '#991b1b',
  },
  orderStatusGo: {
    backgroundColor: '#dbeafe',
    color: '#1d4ed8',
  },
  orderStatusPending: {
    backgroundColor: '#fef9c3',
    color: '#854d0e',
  },
  orderCardItems: {
    marginTop: 8,
    color: '#475569',
    fontSize: 12.5,
    lineHeight: 17,
  },
  orderCardFooter: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  orderCardTotal: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  orderCardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 6,
    flexShrink: 1,
  },
  orderActionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: '#eef4ff',
  },
  orderActionBtnText: {
    color: '#1d4ed8',
    fontSize: 11.5,
    fontWeight: '700',
  },
  orderActionDanger: {
    borderColor: '#fecaca',
    backgroundColor: '#fff5f5',
  },
  orderActionDangerText: {
    color: '#b91c1c',
  },
  cancelOrderCard: {
    margin: 16,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 18,
  },
  cancelSummaryRow: {
    marginTop: 10,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  cancelSummaryLabel: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  cancelInputLabel: {
    marginTop: 12,
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
  },
  cancelInput: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#d5dce7',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#0f172a',
    fontSize: 14,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  cancelActionsRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  cancelSecondary: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelSecondaryText: {
    color: '#334155',
    fontSize: 15,
    fontWeight: '800',
  },
  cancelDanger: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#dc2626',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelDangerText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  checkoutCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e6e9ef',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 12,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  checkoutSectionTitle: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  checkoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  checkoutRowText: {
    flex: 1,
  },
  checkoutRowLabel: {
    color: '#64748b',
    fontSize: 11.5,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  checkoutRowValue: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 3,
  },
  checkoutRowArrow: {
    color: '#cbd5e1',
    fontSize: 18,
    fontWeight: '700',
    paddingLeft: 8,
  },
  couponRow: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
  },
  couponInput: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#0f172a',
    fontSize: 14,
    marginBottom: 6,
    backgroundColor: '#fafbfc',
  },
  addressOption: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#dfe4ec',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
  },
  addressOptionSelected: {
    borderColor: '#3479ed',
    backgroundColor: '#eff6ff',
  },
  addressOptionMain: {
    flex: 1,
  },
  addressOptionLabel: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '800',
  },
  addressOptionDetail: {
    color: '#475569',
    fontSize: 12,
    marginTop: 2,
  },
  addressOptionActions: {
    flexDirection: 'column',
    gap: 4,
    marginLeft: 6,
  },
  addressSetDefault: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    alignItems: 'center',
  },
  addressSetDefaultText: {
    color: '#334155',
    fontSize: 10,
    fontWeight: '800',
  },
  addressDeleteBtn: {
    borderColor: '#fecaca',
    backgroundColor: '#fff5f5',
  },
  addressDeleteText: {
    color: '#b91c1c',
    fontSize: 10,
    fontWeight: '800',
  },
  addressAddBtn: {
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    backgroundColor: '#eef4ff',
  },
  addressAddBtnText: {
    color: '#1d4ed8',
    fontSize: 13,
    fontWeight: '700',
  },
  addressForm: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#f8fafc',
  },
  addressDefaultToggle: {
    paddingVertical: 6,
  },
  addressDefaultToggleText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
  },
  failModalCardClient: {
    margin: 16,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 18,
  },
  paymentOption: {
    borderWidth: 1,
    borderColor: '#dfe4ec',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginTop: 8,
  },
  paymentOptionSelected: {
    borderColor: '#3479ed',
    backgroundColor: '#eff6ff',
  },
  paymentOptionText: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '700',
  },
  paymentOptionTextSelected: {
    color: '#1d4ed8',
    fontWeight: '900',
  },
  optionGroupCard: {
    borderWidth: 1,
    borderColor: '#dfe4ec',
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
    backgroundColor: '#f8fafc',
  },
  optionGroupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  optionGroupName: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '800',
  },
  optionGroupRule: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
  optionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  optionRowChecked: {
    backgroundColor: '#eff6ff',
  },
  optionRowText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '600',
  },
  optionRowTextChecked: {
    color: '#1d4ed8',
    fontWeight: '800',
  },
  optionRowPrice: {
    color: '#64748b',
    fontSize: 12,
  },
  optionQuantityRow: {
    marginTop: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  paymentCountdown: {
    marginTop: 14,
    borderRadius: 14,
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fde68a',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  paymentCountdownLabel: {
    color: '#92400e',
    fontSize: 13,
    fontWeight: '700',
  },
  paymentCountdownValue: {
    color: '#92400e',
    fontSize: 28,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  paymentCountdownDanger: {
    color: '#b91c1c',
  },
  confirmSummary: {
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  starsRow: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  starButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  starText: {
    fontSize: 30,
    color: '#cbd5e1',
  },
  starTextActive: {
    color: '#f59e0b',
  },
  ratingLabel: {
    marginTop: 4,
    color: '#475569',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  chatButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  chatButton: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: '#eef4ff',
    alignItems: 'center',
  },
  chatButtonText: {
    color: '#1d4ed8',
    fontSize: 12.5,
    fontWeight: '700',
  },
  chatBubble: {
    maxWidth: '78%',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 8,
  },
  chatBubbleMine: {
    alignSelf: 'flex-end',
    backgroundColor: '#3479ed',
  },
  chatBubbleOther: {
    alignSelf: 'flex-start',
    backgroundColor: '#f1f5f9',
  },
  chatBubbleText: {
    color: '#0f172a',
    fontSize: 14,
  },
  chatBubbleTime: {
    color: '#475569',
    fontSize: 10,
    marginTop: 4,
    textAlign: 'right',
  },
  chatComposeRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    marginTop: 8,
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#d5dce7',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#0f172a',
    fontSize: 14,
    minHeight: 44,
    maxHeight: 100,
  },
  chatSendBtn: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#3479ed',
  },
  chatSendBtnText: {
    color: '#ffffff',
    fontWeight: '800',
  },
})
